### ISSUE TITLE
please solve my problem , its installed 2 hours ago

### ISSUE THREAD

**Issue by sysserviceallover** [fleetbase/fleetbase#311]
https://app.logihub.tech/

I checked this from chrome, and window 10

Uncaught (in promise) Error: Expected id to be a string or number, received null
at G (vendor-75504771a460d980b64e535e3424211f.js:5748:97)
at M.peekRecord (vendor-75504771a460d980b64e535e3424211f.js:6096:109)
at z.getCompany (vendor-75504771a460d980b64e535e3424211f.js:6544:141)
at new u (vendor-75504771a460d980b64e535e3424211f.js:7651:566)
at h.createComponent (vendor-75504771a460d980b64e535e3424211f.js:9067:181)
at h.createComponent (vendor-75504771a460d980b64e535e3424211f.js:9080:92)
at V.create (vendor-75504771a460d980b64e535e3424211f.js:1754:104)
at Object.evaluate (vendor-75504771a460d980b64e535e3424211f.js:2249:9)
at Object.evaluate (vendor-75504771a460d980b64e535e3424211f.js:2102:13)
at At.evaluateSyscall (vendor-75504771a460d980b64e535e3424211f.js:2374:61)
G @ vendor-75504771a460d980b64e535e3424211f.js:5748
peekRecord @ vendor-75504771a460d980b64e535e3424211f.js:6096
getCompany @ vendor-75504771a460d980b64e535e3424211f.js:6544
u @ vendor-75504771a460d980b64e535e3424211f.js:7651
createComponent @ vendor-75504771a460d980b64e535e3424211f.js:9067
createComponent @ vendor-75504771a460d980b64e535e3424211f.js:9080
create @ vendor-75504771a460d980b64e535e3424211f.js:1754
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:2249
evaluate @ vendor-75504771a460d980b64e535e3424211f.js:2102
evaluateSyscall @ vendor-75504771a460d980b64e535e3424211f.js:2374
evaluateInner @ vendor-75504771a460d980b64e535e3424211f.js:2368
evaluateOuter @ vendor-75504771a460d980b64e535e3424211f.js:2368
next @ vendor-75504771a460d980b64e535e3424211f.js:2426
_execute @ vendor-75504771a460d980b64e535e3424211f.js:2425
execute @ vendor-75504771a460d980b64e535e3424211f.js:2424
handleException @ vendor-75504771a460d980b64e535e3424211f.js:2378
handleException @ vendor-75504771a460d980b64e535e3424211f.js:2393
throw @ vendor-75504771a460d980b64e535e3424211f.js:2376
evaluate @ vendor-75504771a460d980b64e535e3424211f.js:2189
_execute @ vendor-75504771a460d980b64e535e3424211f.js:2376
execute @ vendor-75504771a460d980b64e535e3424211f.js:2374
rerender @ vendor-75504771a460d980b64e535e3424211f.js:2394
render @ vendor-75504771a460d980b64e535e3424211f.js:405
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:430
jt @ vendor-75504771a460d980b64e535e3424211f.js:2364
_renderRoots @ vendor-75504771a460d980b64e535e3424211f.js:429
_renderRootsTransaction @ vendor-75504771a460d980b64e535e3424211f.js:434
_revalidate @ vendor-75504771a460d980b64e535e3424211f.js:436
invoke @ vendor-75504771a460d980b64e535e3424211f.js:2710
flush @ vendor-75504771a460d980b64e535e3424211f.js:2702
flush @ vendor-75504771a460d980b64e535e3424211f.js:2713
_end @ vendor-75504771a460d980b64e535e3424211f.js:2764
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_ensureInstance @ vendor-75504771a460d980b64e535e3424211f.js:2776
ensureInstance @ vendor-75504771a460d980b64e535e3424211f.js:2761
scheduleRevalidate @ vendor-75504771a460d980b64e535e3424211f.js:311
dirtyTag @ vendor-75504771a460d980b64e535e3424211f.js:2602
M @ vendor-75504771a460d980b64e535e3424211f.js:2613
T @ vendor-75504771a460d980b64e535e3424211f.js:539
N @ vendor-75504771a460d980b64e535e3424211f.js:542
Pe @ vendor-75504771a460d980b64e535e3424211f.js:623
Oe @ vendor-75504771a460d980b64e535e3424211f.js:622
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:516
R @ vendor-75504771a460d980b64e535e3424211f.js:544
e.setProperties @ vendor-75504771a460d980b64e535e3424211f.js:515
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:1254
Promise.then
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:1254
set @ vendor-75504771a460d980b64e535e3424211f.js:1254
_set @ vendor-75504771a460d980b64e535e3424211f.js:604
set @ vendor-75504771a460d980b64e535e3424211f.js:600
y @ vendor-75504771a460d980b64e535e3424211f.js:1104
create @ vendor-75504771a460d980b64e535e3424211f.js:1114
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:5957
Ze @ vendor-75504771a460d980b64e535e3424211f.js:5957
findRecord @ vendor-75504771a460d980b64e535e3424211f.js:6092
model @ console-d4a2b230e17210d58027c220a55efdc0.js:589
deserialize @ vendor-75504771a460d980b64e535e3424211f.js:1409
getModel @ vendor-75504771a460d980b64e535e3424211f.js:2996
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:2978
w @ vendor-75504771a460d980b64e535e3424211f.js:3133
v @ vendor-75504771a460d980b64e535e3424211f.js:3131
invoke @ vendor-75504771a460d980b64e535e3424211f.js:2710
flush @ vendor-75504771a460d980b64e535e3424211f.js:2702
flush @ vendor-75504771a460d980b64e535e3424211f.js:2713
_end @ vendor-75504771a460d980b64e535e3424211f.js:2764
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_ensureInstance @ vendor-75504771a460d980b64e535e3424211f.js:2776
schedule @ vendor-75504771a460d980b64e535e3424211f.js:2739
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:667
b @ vendor-75504771a460d980b64e535e3424211f.js:3129
f @ vendor-75504771a460d980b64e535e3424211f.js:3127
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:3151
e.onload @ vendor-75504771a460d980b64e535e3424211f.js:4279
load
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:4279
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:3151
k @ vendor-75504771a460d980b64e535e3424211f.js:3151
g @ vendor-75504771a460d980b64e535e3424211f.js:4279
text @ vendor-75504771a460d980b64e535e3424211f.js:4292
json @ vendor-75504771a460d980b64e535e3424211f.js:4296
parseJSON @ vendor-75504771a460d980b64e535e3424211f.js:6571
await in parseJSON
w @ vendor-75504771a460d980b64e535e3424211f.js:3133
v @ vendor-75504771a460d980b64e535e3424211f.js:3131
invoke @ vendor-75504771a460d980b64e535e3424211f.js:2710
flush @ vendor-75504771a460d980b64e535e3424211f.js:2702
flush @ vendor-75504771a460d980b64e535e3424211f.js:2713
_end @ vendor-75504771a460d980b64e535e3424211f.js:2764
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_ensureInstance @ vendor-75504771a460d980b64e535e3424211f.js:2776
schedule @ vendor-75504771a460d980b64e535e3424211f.js:2739
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:667
b @ vendor-75504771a460d980b64e535e3424211f.js:3129
h @ vendor-75504771a460d980b64e535e3424211f.js:3126
f @ vendor-75504771a460d980b64e535e3424211f.js:3129
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:3151
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:4329
setTimeout
c.onload @ vendor-75504771a460d980b64e535e3424211f.js:4329
load
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:4324
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:3151
k @ vendor-75504771a460d980b64e535e3424211f.js:3151
k @ vendor-75504771a460d980b64e535e3424211f.js:4321
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:6573
request @ vendor-75504771a460d980b64e535e3424211f.js:6573
get @ vendor-75504771a460d980b64e535e3424211f.js:6576
loadOrganizations @ vendor-75504771a460d980b64e535e3424211f.js:6541
promiseUser @ vendor-75504771a460d980b64e535e3424211f.js:6540
await in promiseUser
promiseCurrentUser @ vendor-75504771a460d980b64e535e3424211f.js:6636
beforeModel @ console-d4a2b230e17210d58027c220a55efdc0.js:589
await in beforeModel
runBeforeModelHook @ vendor-75504771a460d980b64e535e3424211f.js:2989
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:2978
w @ vendor-75504771a460d980b64e535e3424211f.js:3133
v @ vendor-75504771a460d980b64e535e3424211f.js:3131
invoke @ vendor-75504771a460d980b64e535e3424211f.js:2710
flush @ vendor-75504771a460d980b64e535e3424211f.js:2702
flush @ vendor-75504771a460d980b64e535e3424211f.js:2713
_end @ vendor-75504771a460d980b64e535e3424211f.js:2764
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_end @ vendor-75504771a460d980b64e535e3424211f.js:2765
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_ensureInstance @ vendor-75504771a460d980b64e535e3424211f.js:2776
schedule @ vendor-75504771a460d980b64e535e3424211f.js:2739
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:667
b @ vendor-75504771a460d980b64e535e3424211f.js:3129
f @ vendor-75504771a460d980b64e535e3424211f.js:3127
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:3151
e.onload @ vendor-75504771a460d980b64e535e3424211f.js:4279
load
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:4279
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:3151
k @ vendor-75504771a460d980b64e535e3424211f.js:3151
g @ vendor-75504771a460d980b64e535e3424211f.js:4279
text @ vendor-75504771a460d980b64e535e3424211f.js:4292
json @ vendor-75504771a460d980b64e535e3424211f.js:4296
parseJSON @ vendor-75504771a460d980b64e535e3424211f.js:6571
await in parseJSON
w @ vendor-75504771a460d980b64e535e3424211f.js:3133
v @ vendor-75504771a460d980b64e535e3424211f.js:3131
invoke @ vendor-75504771a460d980b64e535e3424211f.js:2710
flush @ vendor-75504771a460d980b64e535e3424211f.js:2702
flush @ vendor-75504771a460d980b64e535e3424211f.js:2713
_end @ vendor-75504771a460d980b64e535e3424211f.js:2764
I._boundAutorunEnd @ vendor-75504771a460d980b64e535e3424211f.js:2722
Promise.then
r @ vendor-75504771a460d980b64e535e3424211f.js:2688
flush @ vendor-75504771a460d980b64e535e3424211f.js:1611
_scheduleAutorun @ vendor-75504771a460d980b64e535e3424211f.js:2778
_ensureInstance @ vendor-75504771a460d980b64e535e3424211f.js:2776
schedule @ vendor-75504771a460d980b64e535e3424211f.js:2739
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:667
b @ vendor-75504771a460d980b64e535e3424211f.js:3129
h @ vendor-75504771a460d980b64e535e3424211f.js:3126
f @ vendor-75504771a460d980b64e535e3424211f.js:3129
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:3151
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:4329
setTimeout
c.onload @ vendor-75504771a460d980b64e535e3424211f.js:4329
load
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:4324
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:3151
k @ vendor-75504771a460d980b64e535e3424211f.js:3151
k @ vendor-75504771a460d980b64e535e3424211f.js:4321
(anonymous) @ vendor-75504771a460d980b64e535e3424211f.js:6573
request @ vendor-75504771a460d980b64e535e3424211f.js:6573
post @ vendor-75504771a460d980b64e535e3424211f.js:6580
authenticate @ vendor-75504771a460d980b64e535e3424211f.js:6429
authenticate @ chunk.224.678aa5151468c082492f.js:4595
authenticate @ chunk.224.678aa5151468c082492f.js:4631
login @ console-d4a2b230e17210d58027c220a55efdc0.js:168
await in login
onClick @ vendor-75504771a460d980b64e535e3424211f.js:7164

**Comment by sysserviceallover** [comment]
I have installed it on ubuntu 22 LTS,  what is recommeded OS?

**Comment by sysserviceallover** [comment]
also tried on debian 12
