### ISSUE TITLE
Error in console after installation leading to multiple issue

### ISSUE THREAD

**Issue by AtulKekan-developer** [fleetbase/fleetbase#88]
![image](https://github.com/fleetbase/fleetbase/assets/70166263/e0c018b5-54ee-4452-bcc8-7a195ca3be0f)
Continously receiving foll errors for every operation performed on application

socketcluster-client.min.js:106 WebSocket connection to 'wss://localhost:38000/socketcluster/' failed: 
o @ socketcluster-client.min.js:106
contents.c10c11b1.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getInlineAnchor')
    at contents.c10c11b1.js:1:75818
    at contents.c10c11b1.js:1:76991
    at contents.c10c11b1.js:1:77701
vendor-63a3d8d38b88668df69261499c1985a4.js:3363 Uncaught Error: There is no route named console.
    at H.handlersFor (vendor-63a3d8d38b88668df69261499c1985a4.js:3363:13)
    at E.applyToState (vendor-63a3d8d38b88668df69261499c1985a4.js:3487:238)
    at a.applyIntent (vendor-63a3d8d38b88668df69261499c1985a4.js:3575:10)
    at P (vendor-63a3d8d38b88668df69261499c1985a4.js:1168:259)
    at o._prepareQueryParams (vendor-63a3d8d38b88668df69261499c1985a4.js:1132:126)
    at s.normalizeQueryParams (vendor-63a3d8d38b88668df69261499c1985a4.js:912:73)
    at s._generateURL (vendor-63a3d8d38b88668df69261499c1985a4.js:913:36)
    at s.generateURL (vendor-63a3d8d38b88668df69261499c1985a4.js:913:182)
    at o.<anonymous> (vendor-63a3d8d38b88668df69261499c1985a4.js:6357:10)
    at vendor-63a3d8d38b88668df69261499c1985a4.js:696:67

Even after adding places in application
![image](https://github.com/fleetbase/fleetbase/assets/70166263/d09ccfae-381f-45b5-9bb7-d2df7a3f5b29)
Cannot select them for pickup and dropoff
![image](https://github.com/fleetbase/fleetbase/assets/70166263/b5b9dc1f-d14b-47c6-b090-a9621e0e1cfc)

After registration did not receive verification code on email

**Comment by roncodes** [comment]
1. **Configure Fleetbase** - You need to go to Admin section and configure, email will not work without email configured. Places selection will not work without Google API Key.
2. **Websocket Connection** - Your WebSocket is trying to make a secure connection over localhost, unless you have an ssl certificate registered to your localhost you should set in your environment variable `SOCKETCLUSTER_SECURE` to false
3. Make sure you socket is running by visiting http://localhost:38000

**Comment by AtulKekan-developer** [comment]
Thank you
But where is admin section ?
Where to set Google API Key ?
